stages:
  - test

variables:
  DOCKER_TLS_CERTDIR: "/certs"

test_with_docker:
  stage: test
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t process-manager-test .
    - docker run --rm process-manager-test
