import type { Metadata } from "next";
import "./globals.css";
import Providers from "../components/Providers";

// Self-hosted fonts (no Google Fonts dependency)
import "@fontsource/inter";      // Inter sans-serif font
import "@fontsource/fira-mono";  // Fira Code monospace font

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      style={{ fontFamily: "'Inter', system-ui, -apple-system, sans-serif", fontFeatureSettings: "cv11" }}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
